const express = require("express");
const router = express.Router();
const { body, validationResult } = require("express-validator");

router.get("/", async (req, res) => {
  try {
    const data = {
      Orders: [
        {
          Row_ID: "1",
          Order_ID: "CA-2016-152156",
          Order_Date: "11/8/16",
          Ship_Date: "11/11/16",
          Ship_Mode: "Second Class",
          Customer_ID: "CG-12520",
          First_Name: "Claire",
          Last_Name: "Gute",
          Segment: "Consumer",
          Country: "United States",
          City: "Henderson",
          State: "Kentucky",
          Postal_Code: "42420",
          Region: "South",
          Product_ID: "FUR-BO-10001798",
          Category: "Furniture",
          Sub_Category: "Bookcases",
          Product_Name: "Bush Somerset Collection Bookcase",
          Sales: "261.96",
          Quantity: "2",
          Discount: "0",
          Profit: "41.9136",
        },
        {
          Row_ID: "2",
          Order_ID: "CA-2016-152156",
          Order_Date: "11/8/16",
          Ship_Date: "11/11/16",
          Ship_Mode: "Second Class",
          Customer_ID: "CG-12520",
          First_Name: "Claire",
          Last_Name: "Gute",
          Segment: "Consumer",
          Country: "United States",
          City: "Henderson",
          State: "Kentucky",
          Postal_Code: "42420",
          Region: "South",
          Product_ID: "FUR-CH-10000454",
          Category: "Furniture",
          Sub_Category: "Chairs",
          Product_Name:
            "Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back",
          Sales: "731.94",
          Quantity: "3",
          Discount: "0",
          Profit: "219.582",
        },
        {
          Row_ID: "3",
          Order_ID: "CA-2016-138688",
          Order_Date: "6/12/16",
          Ship_Date: "6/16/16",
          Ship_Mode: "Second Class",
          Customer_ID: "DV-13045",
          First_Name: "Darrin",
          Last_Name: "Van",
          Segment: "Corporate",
          Country: "United States",
          City: "Los Angeles",
          State: "California",
          Postal_Code: "90036",
          Region: "West",
          Product_ID: "OFF-LA-10000240",
          Category: "Office Supplies",
          Sub_Category: "Labels",
          Product_Name:
            "Self-Adhesive Address Labels for Typewriters by Universal",
          Sales: "14.62",
          Quantity: "2",
          Discount: "0",
          Profit: "6.8714",
        },
        {
          Row_ID: "4",
          Order_ID: "US-2015-108966",
          Order_Date: "10/11/15",
          Ship_Date: "10/18/15",
          Ship_Mode: "Standard Class",
          Customer_ID: "SO-20335",
          First_Name: "Sean",
          Last_Name: "O'Donnell",
          Segment: "Consumer",
          Country: "United States",
          City: "Fort Lauderdale",
          State: "Florida",
          Postal_Code: "33311",
          Region: "South",
          Product_ID: "FUR-TA-10000577",
          Category: "Furniture",
          Sub_Category: "Tables",
          Product_Name: "Bretford CR4500 Series Slim Rectangular Table",
          Sales: "957.5775",
          Quantity: "5",
          Discount: "0.45",
          Profit: "-383.031",
        },
        {
          Row_ID: "5",
          Order_ID: "US-2015-108966",
          Order_Date: "10/11/15",
          Ship_Date: "10/18/15",
          Ship_Mode: "Standard Class",
          Customer_ID: "SO-20335",
          First_Name: "Sean",
          Last_Name: "O'Donnell",
          Segment: "Consumer",
          Country: "United States",
          City: "Fort Lauderdale",
          State: "Florida",
          Postal_Code: "33311",
          Region: "South",
          Product_ID: "OFF-ST-10000760",
          Category: "Office Supplies",
          Sub_Category: "Storage",
          Product_Name: "Eldon Fold 'N Roll Cart System",
          Sales: "22.368",
          Quantity: "2",
          Discount: "0.2",
          Profit: "2.5164",
        },
        {
          Row_ID: "6",
          Order_ID: "CA-2014-115812",
          Order_Date: "6/9/14",
          Ship_Date: "6/14/14",
          Ship_Mode: "Standard Class",
          Customer_ID: "BH-11710",
          First_Name: "Brosina",
          Last_Name: "Hoffman",
          Segment: "Consumer",
          Country: "United States",
          City: "Los Angeles",
          State: "California",
          Postal_Code: "90032",
          Region: "West",
          Product_ID: "FUR-FU-10001487",
          Category: "Furniture",
          Sub_Category: "Furnishings",
          Product_Name:
            "Eldon Expressions Wood and Plastic Desk Accessories, Cherry Wood",
          Sales: "48.86",
          Quantity: "7",
          Discount: "0",
          Profit: "14.1694",
        },
        {
          Row_ID: "7",
          Order_ID: "CA-2014-115812",
          Order_Date: "6/9/14",
          Ship_Date: "6/14/14",
          Ship_Mode: "Standard Class",
          Customer_ID: "BH-11710",
          First_Name: "Brosina",
          Last_Name: "Hoffman",
          Segment: "Consumer",
          Country: "United States",
          City: "Los Angeles",
          State: "California",
          Postal_Code: "90032",
          Region: "West",
          Product_ID: "OFF-AR-10002833",
          Category: "Office Supplies",
          Sub_Category: "Art",
          Product_Name: "Newell 322",
          Sales: "7.28",
          Quantity: "4",
          Discount: "0",
          Profit: "1.9656",
        },
        {
          Row_ID: "8",
          Order_ID: "CA-2014-115812",
          Order_Date: "6/9/14",
          Ship_Date: "6/14/14",
          Ship_Mode: "Standard Class",
          Customer_ID: "BH-11710",
          First_Name: "Brosina",
          Last_Name: "Hoffman",
          Segment: "Consumer",
          Country: "United States",
          City: "Los Angeles",
          State: "California",
          Postal_Code: "90032",
          Region: "West",
          Product_ID: "TEC-PH-10002275",
          Category: "Technology",
          Sub_Category: "Phones",
          Product_Name: "Mitel 5320 IP Phone VoIP phone",
          Sales: "907.152",
          Quantity: "6",
          Discount: "0.2",
          Profit: "90.7152",
        },
        {
          Row_ID: "9",
          Order_ID: "CA-2014-115812",
          Order_Date: "6/9/14",
          Ship_Date: "6/14/14",
          Ship_Mode: "Standard Class",
          Customer_ID: "BH-11710",
          First_Name: "Brosina",
          Last_Name: "Hoffman",
          Segment: "Consumer",
          Country: "United States",
          City: "Los Angeles",
          State: "California",
          Postal_Code: "90032",
          Region: "West",
          Product_ID: "OFF-BI-10003910",
          Category: "Office Supplies",
          Sub_Category: "Binders",
          Product_Name: "DXL Angle-View Binders with Locking Rings by Samsill",
          Sales: "18.504",
          Quantity: "3",
          Discount: "0.2",
          Profit: "5.7825",
        },
        {
          Row_ID: "10",
          Order_ID: "CA-2014-115812",
          Order_Date: "6/9/14",
          Ship_Date: "6/14/14",
          Ship_Mode: "Standard Class",
          Customer_ID: "BH-11710",
          First_Name: "Brosina",
          Last_Name: "Hoffman",
          Segment: "Consumer",
          Country: "United States",
          City: "Los Angeles",
          State: "California",
          Postal_Code: "90032",
          Region: "West",
          Product_ID: "OFF-AP-10002892",
          Category: "Office Supplies",
          Sub_Category: "Appliances",
          Product_Name: "Belkin F5C206VTEL 6 Outlet Surge",
          Sales: "114.9",
          Quantity: "5",
          Discount: "0",
          Profit: "34.47",
        },
        {
          Row_ID: "11",
          Order_ID: "CA-2014-115812",
          Order_Date: "6/9/14",
          Ship_Date: "6/14/14",
          Ship_Mode: "Standard Class",
          Customer_ID: "BH-11710",
          First_Name: "Brosina",
          Last_Name: "Hoffman",
          Segment: "Consumer",
          Country: "United States",
          City: "Los Angeles",
          State: "California",
          Postal_Code: "90032",
          Region: "West",
          Product_ID: "FUR-TA-10001539",
          Category: "Furniture",
          Sub_Category: "Tables",
          Product_Name: "Chromcraft Rectangular Conference Tables",
          Sales: "1706.184",
          Quantity: "9",
          Discount: "0.2",
          Profit: "85.3092",
        },
        {
          Row_ID: "12",
          Order_ID: "CA-2014-115812",
          Order_Date: "6/9/14",
          Ship_Date: "6/14/14",
          Ship_Mode: "Standard Class",
          Customer_ID: "BH-11710",
          First_Name: "Brosina",
          Last_Name: "Hoffman",
          Segment: "Consumer",
          Country: "United States",
          City: "Los Angeles",
          State: "California",
          Postal_Code: "90032",
          Region: "West",
          Product_ID: "TEC-PH-10002033",
          Category: "Technology",
          Sub_Category: "Phones",
          Product_Name: "Konftel 250 Conference phone - Charcoal black",
          Sales: "911.424",
          Quantity: "4",
          Discount: "0.2",
          Profit: "68.3568",
        },
        {
          Row_ID: "13",
          Order_ID: "CA-2017-114412",
          Order_Date: "4/15/17",
          Ship_Date: "4/20/17",
          Ship_Mode: "Standard Class",
          Customer_ID: "AA-10480",
          First_Name: "Andrew",
          Last_Name: "Allen",
          Segment: "Consumer",
          Country: "United States",
          City: "Concord",
          State: "North Carolina",
          Postal_Code: "28027",
          Region: "South",
          Product_ID: "OFF-PA-10002365",
          Category: "Office Supplies",
          Sub_Category: "Paper",
          Product_Name: "Xerox 1967",
          Sales: "15.552",
          Quantity: "3",
          Discount: "0.2",
          Profit: "5.4432",
        },
        {
          Row_ID: "14",
          Order_ID: "CA-2016-161389",
          Order_Date: "12/5/16",
          Ship_Date: "12/10/16",
          Ship_Mode: "Standard Class",
          Customer_ID: "IM-15070",
          First_Name: "Irene",
          Last_Name: "Maddox",
          Segment: "Consumer",
          Country: "United States",
          City: "Seattle",
          State: "Washington",
          Postal_Code: "98103",
          Region: "West",
          Product_ID: "OFF-BI-10003656",
          Category: "Office Supplies",
          Sub_Category: "Binders",
          Product_Name: "Fellowes PB200 Plastic Comb Binding Machine",
          Sales: "407.976",
          Quantity: "3",
          Discount: "0.2",
          Profit: "132.5922",
        },
        {
          Row_ID: "15",
          Order_ID: "US-2015-118983",
          Order_Date: "11/22/15",
          Ship_Date: "11/26/15",
          Ship_Mode: "Standard Class",
          Customer_ID: "HP-14815",
          First_Name: "Harold",
          Last_Name: "Pawlan",
          Segment: "Home Office",
          Country: "United States",
          City: "Fort Worth",
          State: "Texas",
          Postal_Code: "76106",
          Region: "Central",
          Product_ID: "OFF-AP-10002311",
          Category: "Office Supplies",
          Sub_Category: "Appliances",
          Product_Name:
            "Holmes Replacement Filter for HEPA Air Cleaner, Very Large Room, HEPA Filter",
          Sales: "68.81",
          Quantity: "5",
          Discount: "0.8",
          Profit: "-123.858",
        },
        {
          Row_ID: "16",
          Order_ID: "US-2015-118983",
          Order_Date: "11/22/15",
          Ship_Date: "11/26/15",
          Ship_Mode: "Standard Class",
          Customer_ID: "HP-14815",
          First_Name: "Harold",
          Last_Name: "Pawlan",
          Segment: "Home Office",
          Country: "United States",
          City: "Fort Worth",
          State: "Texas",
          Postal_Code: "76106",
          Region: "Central",
          Product_ID: "OFF-BI-10000756",
          Category: "Office Supplies",
          Sub_Category: "Binders",
          Product_Name: "Storex DuraTech Recycled Plastic Frosted Binders",
          Sales: "2.544",
          Quantity: "3",
          Discount: "0.8",
          Profit: "-3.816",
        },
        {
          Row_ID: "17",
          Order_ID: "CA-2014-105893",
          Order_Date: "11/11/14",
          Ship_Date: "11/18/14",
          Ship_Mode: "Standard Class",
          Customer_ID: "PK-19075",
          First_Name: "Pete",
          Last_Name: "Kriz",
          Segment: "Consumer",
          Country: "United States",
          City: "Madison",
          State: "Wisconsin",
          Postal_Code: "53711",
          Region: "Central",
          Product_ID: "OFF-ST-10004186",
          Category: "Office Supplies",
          Sub_Category: "Storage",
          Product_Name:
            "Stur-D-Stor Shelving, Vertical 5-Shelf: 72'H x 36'W x 18 1/2",
          Sales: "665.88",
          Quantity: "6",
          Discount: "0",
          Profit: "13.3176",
        },
        {
          Row_ID: "18",
          Order_ID: "CA-2014-167164",
          Order_Date: "5/13/14",
          Ship_Date: "5/15/14",
          Ship_Mode: "Second Class",
          Customer_ID: "AG-10270",
          First_Name: "Alejandro",
          Last_Name: "Grove",
          Segment: "Consumer",
          Country: "United States",
          City: "West Jordan",
          State: "Utah",
          Postal_Code: "84084",
          Region: "West",
          Product_ID: "OFF-ST-10000107",
          Category: "Office Supplies",
          Sub_Category: "Storage",
          Product_Name: "Fellowes Super Stor/Drawer",
          Sales: "55.5",
          Quantity: "2",
          Discount: "0",
          Profit: "9.99",
        },
        {
          Row_ID: "19",
          Order_ID: "CA-2014-143336",
          Order_Date: "8/27/14",
          Ship_Date: "9/1/14",
          Ship_Mode: "Second Class",
          Customer_ID: "ZD-21925",
          First_Name: "Zuschuss",
          Last_Name: "Donatelli",
          Segment: "Consumer",
          Country: "United States",
          City: "San Francisco",
          State: "California",
          Postal_Code: "94109",
          Region: "West",
          Product_ID: "OFF-AR-10003056",
          Category: "Office Supplies",
          Sub_Category: "Art",
          Product_Name: "Newell 341",
          Sales: "8.56",
          Quantity: "2",
          Discount: "0",
          Profit: "2.4824",
        },
        {
          Row_ID: "20",
          Order_ID: "CA-2014-143336",
          Order_Date: "8/27/14",
          Ship_Date: "9/1/14",
          Ship_Mode: "Second Class",
          Customer_ID: "ZD-21925",
          First_Name: "Zuschuss",
          Last_Name: "Donatelli",
          Segment: "Consumer",
          Country: "United States",
          City: "San Francisco",
          State: "California",
          Postal_Code: "94109",
          Region: "West",
          Product_ID: "TEC-PH-10001949",
          Category: "Technology",
          Sub_Category: "Phones",
          Product_Name: "Cisco SPA 501G IP Phone",
          Sales: "213.48",
          Quantity: "3",
          Discount: "0.2",
          Profit: "16.011",
        },
        {
          Row_ID: "21",
          Order_ID: "CA-2014-143336",
          Order_Date: "8/27/14",
          Ship_Date: "9/1/14",
          Ship_Mode: "Second Class",
          Customer_ID: "ZD-21925",
          First_Name: "Zuschuss",
          Last_Name: "Donatelli",
          Segment: "Consumer",
          Country: "United States",
          City: "San Francisco",
          State: "California",
          Postal_Code: "94109",
          Region: "West",
          Product_ID: "OFF-BI-10002215",
          Category: "Office Supplies",
          Sub_Category: "Binders",
          Product_Name: "Wilson Jones Hanging View Binder, White, 1",
          Sales: "22.72",
          Quantity: "4",
          Discount: "0.2",
          Profit: "7.384",
        },
        {
          Row_ID: "22",
          Order_ID: "CA-2016-137330",
          Order_Date: "12/9/16",
          Ship_Date: "12/13/16",
          Ship_Mode: "Standard Class",
          Customer_ID: "KB-16585",
          First_Name: "Ken",
          Last_Name: "Black",
          Segment: "Corporate",
          Country: "United States",
          City: "Fremont",
          State: "Nebraska",
          Postal_Code: "68025",
          Region: "Central",
          Product_ID: "OFF-AR-10000246",
          Category: "Office Supplies",
          Sub_Category: "Art",
          Product_Name: "Newell 318",
          Sales: "19.46",
          Quantity: "7",
          Discount: "0",
          Profit: "5.0596",
        },
        {
          Row_ID: "23",
          Order_ID: "CA-2016-137330",
          Order_Date: "12/9/16",
          Ship_Date: "12/13/16",
          Ship_Mode: "Standard Class",
          Customer_ID: "KB-16585",
          First_Name: "Ken",
          Last_Name: "Black",
          Segment: "Corporate",
          Country: "United States",
          City: "Fremont",
          State: "Nebraska",
          Postal_Code: "68025",
          Region: "Central",
          Product_ID: "OFF-AP-10001492",
          Category: "Office Supplies",
          Sub_Category: "Appliances",
          Product_Name: "Acco Six-Outlet Power Strip, 4' Cord Length",
          Sales: "60.34",
          Quantity: "7",
          Discount: "0",
          Profit: "15.6884",
        },
        {
          Row_ID: "24",
          Order_ID: "US-2017-156909",
          Order_Date: "7/16/17",
          Ship_Date: "7/18/17",
          Ship_Mode: "Second Class",
          Customer_ID: "SF-20065",
          First_Name: "Sandra",
          Last_Name: "Flanagan",
          Segment: "Consumer",
          Country: "United States",
          City: "Philadelphia",
          State: "Pennsylvania",
          Postal_Code: "19140",
          Region: "East",
          Product_ID: "FUR-CH-10002774",
          Category: "Furniture",
          Sub_Category: "Chairs",
          Product_Name: "Global Deluxe Stacking Chair, Gray",
          Sales: "71.372",
          Quantity: "2",
          Discount: "0.3",
          Profit: "-1.0196",
        },
        {
          Row_ID: "25",
          Order_ID: "CA-2015-106320",
          Order_Date: "9/25/15",
          Ship_Date: "9/30/15",
          Ship_Mode: "Standard Class",
          Customer_ID: "EB-13870",
          First_Name: "Emily",
          Last_Name: "Burns",
          Segment: "Consumer",
          Country: "United States",
          City: "Orem",
          State: "Utah",
          Postal_Code: "84057",
          Region: "West",
          Product_ID: "FUR-TA-10000577",
          Category: "Furniture",
          Sub_Category: "Tables",
          Product_Name: "Bretford CR4500 Series Slim Rectangular Table",
          Sales: "1044.63",
          Quantity: "3",
          Discount: "0",
          Profit: "240.2649",
        },
        {
          Row_ID: "26",
          Order_ID: "CA-2016-121755",
          Order_Date: "1/16/16",
          Ship_Date: "1/20/16",
          Ship_Mode: "Second Class",
          Customer_ID: "EH-13945",
          First_Name: "Eric",
          Last_Name: "Hoffmann",
          Segment: "Consumer",
          Country: "United States",
          City: "Los Angeles",
          State: "California",
          Postal_Code: "90049",
          Region: "West",
          Product_ID: "OFF-BI-10001634",
          Category: "Office Supplies",
          Sub_Category: "Binders",
          Product_Name: "Wilson Jones Active Use Binders",
          Sales: "11.648",
          Quantity: "2",
          Discount: "0.2",
          Profit: "4.2224",
        },
        {
          Row_ID: "27",
          Order_ID: "CA-2016-121755",
          Order_Date: "1/16/16",
          Ship_Date: "1/20/16",
          Ship_Mode: "Second Class",
          Customer_ID: "EH-13945",
          First_Name: "Eric",
          Last_Name: "Hoffmann",
          Segment: "Consumer",
          Country: "United States",
          City: "Los Angeles",
          State: "California",
          Postal_Code: "90049",
          Region: "West",
          Product_ID: "TEC-AC-10003027",
          Category: "Technology",
          Sub_Category: "Accessories",
          Product_Name: "Imation 8GB Mini TravelDrive USB 2.0 Flash Drive",
          Sales: "90.57",
          Quantity: "3",
          Discount: "0",
          Profit: "11.7741",
        },
        {
          Row_ID: "28",
          Order_ID: "US-2015-150630",
          Order_Date: "9/17/15",
          Ship_Date: "9/21/15",
          Ship_Mode: "Standard Class",
          Customer_ID: "TB-21520",
          First_Name: "Tracy",
          Last_Name: "Blumstein",
          Segment: "Consumer",
          Country: "United States",
          City: "Philadelphia",
          State: "Pennsylvania",
          Postal_Code: "19140",
          Region: "East",
          Product_ID: "FUR-BO-10004834",
          Category: "Furniture",
          Sub_Category: "Bookcases",
          Product_Name:
            "Riverside Palais Royal Lawyers Bookcase, Royale Cherry Finish",
          Sales: "3083.43",
          Quantity: "7",
          Discount: "0.5",
          Profit: "-1665.0522",
        },
      ],
    };

    return res.json(data);

    // const data =
  } catch (error) {
    console.error(error.message);
    res.status(500).send("Internal Server Error Occured NJ1");
  }
});

module.exports = router;

// https://www.upwork.com/freelancers/~01622d2986d32625a7
// https://www.upwork.com/freelancers/~01ffe29354362dad50
